# Generated by Django 5.0.3 on 2024-04-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_10', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=40)),
                ('adres', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('team', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(max_length=40)),
                ('experiment_name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('method', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='key_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=100)),
                ('web_adress', models.URLField(max_length=100)),
                ('mail', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='metody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=40)),
                ('pesel', models.IntegerField(max_length=11)),
                ('birth_name', models.DateField()),
                ('adress', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=40)),
                ('parienstscol', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=1)),
                ('diagnosis', models.TextField()),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=60)),
                ('team_leader', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=40)),
                ('telephone_num', models.IntegerField(max_length=12)),
            ],
        ),
    ]
