# Generated by Django 5.0.3 on 2024-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='pesel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='telephone_num',
            field=models.IntegerField(),
        ),
    ]
