# Generated by Django 5.0.6 on 2024-06-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0002_alter_employes_age_alter_patients_pesel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='key_words',
            new_name='KeyWords',
        ),
    ]
