# Generated by Django 5.0.6 on 2024-06-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0003_rename_key_words_keywords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='metody',
            new_name='Methods',
        ),
    ]
