# Generated by Django 5.0.6 on 2024-06-21 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0005_employee_employeeexperiment_experiment_keyword_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=100)),
                ('web_adress', models.URLField(max_length=100)),
                ('mail', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Methods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=40)),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('birth_name', models.DateField()),
                ('adress', models.CharField(max_length=100)),
                ('mail', models.EmailField(default='write@your.mail', max_length=40)),
                ('parienstscol', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=1)),
                ('diagnosis', models.TextField()),
                ('sex', models.CharField(choices=[('0', 'Not specified'), ('1', 'Male'), ('2', 'Female')], default='0', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='employeeexperiment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='projectemployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='employeeexperiment',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='patientexperiment',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='result',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='project',
        ),
        migrations.RemoveField(
            model_name='patientexperiment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='projectemployee',
            name='project',
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('adres', models.CharField(max_length=100)),
                ('email', models.EmailField(default='email@example.com', max_length=50)),
                ('team', models.CharField(default='Default Team', max_length=40)),
                ('phone_number', models.CharField(default='111111111', max_length=15)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekty.laboratories')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_10', models.CharField(max_length=4)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='projekty.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('paused', 'Paused')], default='ongoing', max_length=10)),
                ('description', models.TextField()),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to='projekty.employes')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('projects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekty.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('paused', 'Paused')], default='ongoing', max_length=10)),
                ('description', models.TextField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty.methods')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty.projects')),
            ],
        ),
        migrations.CreateModel(
            name='RelationEmployesExperiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty.employes')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty.experiments')),
            ],
        ),
        migrations.AddField(
            model_name='experiments',
            name='employe',
            field=models.ManyToManyField(through='projekty.RelationEmployesExperiments', to='projekty.employes'),
        ),
        migrations.CreateModel(
            name='RelationEmployesProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty.employes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty.projects')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='workers',
            field=models.ManyToManyField(through='projekty.RelationEmployesProjects', to='projekty.employes'),
        ),
        migrations.CreateModel(
            name='RelationPatientsExperiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty.experiments')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty.patients')),
            ],
        ),
        migrations.AddField(
            model_name='experiments',
            name='patients',
            field=models.ManyToManyField(through='projekty.RelationPatientsExperiments', to='projekty.patients'),
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeExperiment',
        ),
        migrations.DeleteModel(
            name='Protocol',
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='KeyWord',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientExperiment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectEmployee',
        ),
    ]
