# Generated by Django 5.0.6 on 2024-06-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0009_alter_patients_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='parienstscol',
            new_name='phonenumber',
        ),
    ]
