# Generated by Django 5.0.3 on 2024-06-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0010_rename_parienstscol_patients_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='birth_name',
            new_name='birth_date',
        ),
    ]
